const fs = require('node:fs');
const os = require('node:os');
const root = 'load-tests/results/';
const read = (name) => fs.existsSync(root + name) ? JSON.parse(fs.readFileSync(root + name, 'utf8')) : null;
const stages = ['production-smoke', 'production-10', 'production-50', 'production-100', 'production-250', 'production-500', 'production-static', 'production-soak'];
const rows = stages.map((label) => read(label + '-analysis.json')).filter(Boolean);
const fmt = (n) => n == null ? '—' : Number(n).toFixed(2);
const pct = (n) => fmt(n * 100) + '%';
const preflight = read('production-preflight.json');
const failing = rows.find((r) => r.result === 'FAIL');
const stable = rows.filter((r) => /^production-(10|50|100|250|500)$/.test(r.label) && r.result !== 'FAIL');
const largest = Math.max(0, ...stable.map((r) => r.peakVUs));
const cleanupFiles = fs.readdirSync(root).filter((n) => n.startsWith('production-') && n.endsWith('-cleanup.json'));
const cleanups = cleanupFiles.map((n) => ({ file: n, ...read(n) }));
const duplicate = read('production-duplicates-analysis.json');
const final = read('production-final-verification.json');
let text = `# Production load-test report\n\n`;
text += `## 1. Executive result\n\n500-player verdict: **NOT ESTABLISHED**. ${failing ? `Progressive escalation stopped at **${failing.peakVUs} VUs (${failing.result})**.` : 'No failure point is recorded yet.'} The largest completed progressive cohort with <1% HTTP/gameplay failures is **${largest} players**; latency warnings are retained. This is not a proven 500-player capacity or a deployment-wide limit.\n\n`;
text += `## 2. Test environment and actual journey\n\nExecuted October 6, 2026 UTC (October 6-7 in Asia/Dhaka); final cleanup verified at 17:57:10 UTC.\n\n- Target: ${preflight?.target || 'not recorded'}; owner explicitly authorized production writes and cleanup.\n- Hosting: real Vercel deployment, real configured Appwrite and Redis through unchanged APIs. Preflight response IDs showed the BOM edge and IAD function region.\n- Generator: ${os.cpus()[0].model}, ${os.cpus().length} logical CPUs, ${fmt(os.totalmem() / 2 ** 30)} GiB RAM, Windows ${os.arch()}, Node ${process.version}; portable checksum-verified k6 2.3.0. One generator/public IP.\n- Existing timer: ${preflight?.settings.durationSeconds} seconds; settings were not modified. Initial public aggregates: ${preflight?.baselineStats.totalParticipants} participants, ${preflight?.baselineStats.totalAttempts} attempts.\n- Public players have no login. Home → settings/fastest leaderboard → prefixed registration → play HTML → start → four paced submissions → result HTML/API → leaderboard HTML and five-second refreshes. The fourth submission calculates score; no invented score/level-loading/timer endpoints. Each VU registers once.\n- Pacing: 1–3 seconds before registration, then 5–9/9–15/6–12/4–7 seconds for the levels. No automatic mutation retries.\n- Request latency is k6 HTTP duration, excluding DNS/TCP/TLS setup; it includes request send/wait/receive. Results are from this Bangladesh generator path, not provider-internal timing.\n\n`;
text += `## 3. Test summary\n\n| Stage / peak VUs | Avg ms | P95 ms | P99 ms | Req/s | HTTP success | Semantic errors | Result |\n| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |\n`;
for (const r of rows) text += `| ${r.label} / ${r.peakVUs} | ${fmt(r.latency.avg)} | ${fmt(r.latency.p95)} | ${fmt(r.latency.p99)} | ${fmt(r.requestsPerSecond)} | ${pct(1-r.httpFailureRate)} | ${pct(r.semanticFailureRate)} | ${r.result} |\n`;
if (!read('production-500-analysis.json')) text += '| 500 | — | — | — | — | — | — | NOT RUN: progression gate |\n';
text += '\nThresholds: HTTP, semantic-response and completed-journey failure rates <1%; API P95 <1000 ms/P99 <2000 ms; endpoint P99 <2000 ms. Correctness failures yield FAIL; latency-only crossings yield WARNING, never PASS. Smoke/10/50 used the same targets without early abort. From 100 onward error thresholds abort after a 20-second observation window. Actual k6 threshold exit codes and raw summaries are retained.\n\n';
text += '| Stage | Duration s | Requests | HTTP successful | HTTP failed | Semantic failed | Journeys completed/started | Peak req/s (1 s bin) | Data received bytes | Data sent bytes |\n| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n';
for (const r of rows) text += `| ${r.label} | ${fmt(r.durationSeconds)} | ${r.requests} | ${r.successfulRequests} | ${r.requests-r.successfulRequests} | ${r.semanticFailures} | ${r.journeysCompleted}/${r.journeysStarted} | ${r.peakRequestsPerSecond} | ${r.dataReceived} | ${r.dataSent} |\n`;
text += '\nPeak req/s uses UTC-aligned one-second completion bins, not an instantaneous server-invocation maximum. HTTP 200 with invalid gameplay/result content is also counted as a semantic failure. Abort can interrupt successful in-flight journeys; interrupted players are not reported as completed.\n\n';
text += `## 4. Spike and event-start tests\n\n500-user start spike, 500-user event cohort and 500-user finish/score spike: **NOT RUN** unless progressive 500 succeeds. ${failing ? `The ${failing.peakVUs}-VU failure gate prevented escalation.` : 'Progressive gate has not authorized those executions yet.'} No peak/P95/P99/recovery values are invented.\n\n`;
text += '## 5. Soak test\n\n';
const soak = read('production-soak-analysis.json');
if (soak) {
  text += `${soak.peakVUs} VUs; ${fmt(soak.durationSeconds)} seconds including graceful completion; ${soak.requests} requests; HTTP error ${pct(soak.httpFailureRate)}; semantic error ${pct(soak.semanticFailureRate)}; **${soak.result}**. One game per player, followed by sustained five-second leaderboard polling. This is a lower-concurrency, leaderboard-focused soak, not a continuously mutating 500-player game soak.\n\n| UTC minute | Requests | Avg ms | P95 ms | P99 ms |\n| --- | ---: | ---: | ---: | ---: |\n`;
  for (const m of soak.latencyByMinute) text += `| ${m.utcMinute} | ${m.count} | ${fmt(m.avg)} | ${fmt(m.p95)} | ${fmt(m.p99)} |\n`;
} else text += 'NOT RUN after the failure gate. No sustained-capacity or memory-leak claim is made.\n';
text += '\n## 6. Endpoint report\n\nOperations use real routes: homepage `/`; settings `/api/settings`; registration `/api/register`; start `/api/attempt/start`; levels 1–4 `/api/attempt/submit`; result `/api/attempt?id=...`; leaderboard `/api/leaderboard`. Other rows are their existing HTML pages. No level endpoint or separate score endpoint exists.\n';
for (const r of rows) {
  text += `\n### ${r.label}\n\n| Operation | Requests | Avg ms | Median ms | P90 ms | P95 ms | P99 ms | Min ms | Max ms | HTTP failed | Semantic failure |\n| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n`;
  for (const [name, e] of Object.entries(r.endpoints)) text += `| ${name} | ${e.count} | ${fmt(e.avg)} | ${fmt(e.median)} | ${fmt(e.p90)} | ${fmt(e.p95)} | ${fmt(e.p99)} | ${fmt(e.min)} | ${fmt(e.max)} | ${e.httpFailures} | ${pct(e.semanticFailureRate)} |\n`;
}
text += '\n## 7. Errors and failure gate\n\n| Stage | HTTP 2xx | HTTP 4xx | HTTP 429 | HTTP 5xx | Timeouts | Network errors | Missing completed rank |\n| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n';
for (const r of rows) {
  const count = (lo, hi) => Object.entries(r.statuses).filter(([code]) => +code >= lo && +code <= hi).reduce((s, [, n]) => s+n, 0);
  text += `| ${r.label} | ${count(200,299)} | ${count(400,499)} | ${r.statuses['429'] || 0} | ${count(500,599)} | ${r.timeouts} | ${r.networkErrors} | ${r.missingRanks} |\n`;
}
text += '\nAll statuses, including 429, are retained; failure responses are not filtered out to manufacture a pass. The registration limiter is 120 requests per trusted IP per fixed 60-second window. A single-generator test deliberately does not spoof forwarding headers or disable that policy.\n\n';
text += '## 8. Redis report\n\n| Stage | HIT | MISS | BYPASS | Header hit ratio |\n| --- | ---: | ---: | ---: | ---: |\n';
for (const r of rows) { const c = r.redisCache, n = (c.HIT || 0)+(c.MISS || 0)+(c.BYPASS || 0); text += `| ${r.label} | ${c.HIT || 0} | ${c.MISS || 0} | ${c.BYPASS || 0} | ${n ? pct((c.HIT || 0)/n) : '—'} |\n`; }
text += '\nHIT headers demonstrate the actual shared cache serving leaderboard responses. MISS/BYPASS during mutations/fills remain visible. The cache expires in ten seconds and mutations invalidate it. Provider-internal Redis latency, key counters, memory, command throughput and connection limits: **Not measurable with the currently available monitoring.** No Redis flush or manual key deletion was performed. Normal APIs and cleanup invoke the existing application invalidation/rate-limit behavior.\n\n';
text += '## 9. Database and static traffic\n\nReal Appwrite-backed APIs were exercised. Successful completions/ranks establish externally observed correctness only for the completed cohorts. Provider query latency, database connections/lock contention, internal errors and resource saturation: **Not measurable with the currently available monitoring.** Vercel function duration/concurrency/errors and external API internal latency: **Not measurable with the currently available monitoring.**\n\nThe source scans up to 500 attempts/participants for ranks/stats and does not provide server-side transaction/idempotency guards. These are code findings, not measured provider limits. No schema/query/runtime changes were made. Deployed same-origin asset paths were discovered in preflight; the separate static load scenario was NOT RUN after the failure gate. k6 does not implement browser cache or render the UI; no third-party font traffic is generated. HTML preflight returned a Vercel HIT. Existing hashed assets are immutable and browser-cacheable; audio is synthesized locally and PDF is generated client-side on demand. Browser rendering and paid external media APIs are outside this load test.\n\n';
text += '## 10. First bottleneck and duplicate submissions\n\n';
if (failing) text += `First observed progressive failure: **${failing.label}**, at peak ${failing.peakVUs} VUs. Its status/error table and endpoint rows above identify the failing operations. Of 1,270 requests, 1,172 returned HTTP 403 (92.28%); 98 returned 200. All 26 registration calls returned 403, so no 250-stage player reached start or submission. A subsequent one-request k6 probe returned the title **Vercel Security Checkpoint**, header **x-vercel-mitigated: challenge**, and HTTP 403 in 40.73 ms. This establishes edge challenge mitigation of this automated client, not database exhaustion or failure of 250 genuine browser players. No HTTP 429, 5xx, network error or timeout was observed in the progressive stages. Fast blocked responses explain the lower aggregate latency at 250. Earlier cohorts retained latency warnings in registration/start/submission even without request failures.\n\n`;
if (duplicate) {
  text += `A separate one-participant diagnostic used concurrent starts and final submissions. Simultaneous final submissions accepted: **${duplicate.simultaneousFinalsAccepted}/2**. See \`production-duplicates-analysis.json\` for exact statuses/timestamps and the sequential replay. Both simultaneous finals returned HTTP 200/COMPLETED with different completion times: **9,455 ms and 9,533 ms**. The result API persisted **9,533 ms**, confirming a **78 ms overwrite** of the official completion time. Sequential replay correctly returned HTTP 409 ATTEMPT_ENDED. This is a confirmed terminal-transition race; no duplicate documents or leaderboard entries were observed, and the score itself was not exposed by this API.\n\n| Diagnostic operation | HTTP | Attempt status | Completion ms | Started at | Completed at |\n| --- | ---: | --- | ---: | --- | --- |\n`;
  for (const o of duplicate.outcomes) text += `| ${o.operation} | ${o.status} | ${o.attemptStatus || '—'} | ${o.completionTimeMs ?? '—'} | ${o.startedAt || '—'} | ${o.completedAt || '—'} |\n`;
} else text += 'The normal journey checked duplicate leaderboard IDs; no same-attempt concurrency diagnostic has been recorded yet. Client UI double-tap behavior is not measured by HTTP k6.\n';
text += '\n## 11. Capacity and safety margin\n\nThe largest completed progressive cohort was **100 players**, with zero HTTP/gameplay failures but latency warnings. It is a short-cohort observation, not sustained event capacity. The 250-player automated path failed at Vercel edge mitigation; actual browser capacity at 250 or 500 remains **unverified**. No numerical safe event capacity or safety margin can be certified from these runs. The source registration limit of 120 per trusted IP per minute is an additional untested arrival constraint, not the cause of the observed 403 failures.\n\n';
text += '## 12. Recommendations\n\n- **P0:** Make final submission an atomic, idempotent terminal transition in a separate reviewed change; the diagnostic confirmed completion-time overwrite. No gameplay code was changed during testing.\n- **P0:** Before certifying 500 players, arrange an owner-controlled, narrowly scoped Vercel exception for authorized automation, then repeat 250 and 500 progressively and run the gated spikes. Preserve the current failed results. Vercel documents that challenge responses require a real browser and can block automated clients; this run does not measure browser capacity. [Vercel firewall concepts](https://vercel.com/docs/vercel-firewall/firewall-concepts), [Vercel load-testing guidance](https://vercel.com/kb/guide/how-to-effectively-load-test-your-vercel-application). The owner chose to finish this report with 500 unverified; no protection was bypassed or modified.\n- **P1:** Investigate registration/start/submission latency with provider traces; HTTP timing alone cannot attribute it to Redis, Appwrite or Vercel.\n- **P1:** Review shared event Wi-Fi/NAT behavior against the source 120-registration/minute limit, without spoofing IP headers or silently disabling security. No 429 was observed here.\n- **P1:** Review the source 500-document rank/stat window before adding 500 players to an existing event. This is a code finding, not a measured provider capacity limit.\n- **P2:** Monitor cache HIT/MISS/BYPASS during game mutations. The header hit ratio excludes responses without a cache header, including 931 blocked leaderboard responses in the 250-stage run.\n\nNo application runtime, UI, game rules, security limits, schema, score formula or production settings were changed by this task. Existing uncommitted changes from the earlier performance task remain.\n\n';
text += '### Cleanup evidence\n\n| Run | Planned registrations | Attempts deleted | Participants deleted | Skipped | Unresolved |\n| --- | ---: | ---: | ---: | ---: | ---: |\n';
for (const c of cleanups) text += `| ${c.file} | ${c.planned} | ${c.deletedAttempts.length} | ${c.deletedParticipants.length} | ${c.skipped.length} | ${c.unresolved.length} |\n`;
if (final) text += `\nFinal public aggregate verification: ${final.stats.totalParticipants} participants, ${final.stats.totalAttempts} attempts; baseline ${preflight.baselineStats.totalParticipants}/${preflight.baselineStats.totalAttempts}. Remaining load-test ledger counts: ${JSON.stringify(final.remainingTestCounts)}. This aggregate equality plus exact test-ID cleanup is not a dump of real users' private data.\n`;
text += '\n## 13. Final verdict\n\n**500-player capacity is UNVERIFIED.** The measured cohorts and failure gate above determine the conclusion. The edge challenge prevented a valid 250/500-player backend-capacity test; real-browser and distributed-IP capacity are untested. Do not extrapolate local fixture tests or HTTP 200 averages into a 500-player production pass. Raw k6 summaries, point streams, ledgers and cleanup reports are saved in `load-tests/results`; the suite and operational instructions are in `load-tests/README.md`.\n\nMethod references: [Grafana k6 summaries](https://grafana.com/docs/k6/latest/results-output/end-of-test/custom-summary/) and [ramping VUs](https://grafana.com/docs/k6/latest/using-k6/scenarios/executors/ramping-vus/).\n';
fs.writeFileSync('docs/production-load-test-report.md', text);
console.log('Wrote docs/production-load-test-report.md');
